version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
      - S3_UPLOAD_ENDPOINT=http://s3:9000
    depends_on:
      - db
      - s3
    volumes:
      - ./src/:/app/src
      - ./public/:/app/public
      - ./prisma/:/app/prisma

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "38763:38763"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_REGION_NAME=my-location
    volumes:
      - s3_data:/data
      - s3_config:/root/.minio
      - ./cors.json:/root/.minio/config/cors.json
    command: server /data --console-address ":38763"

volumes:
  postgres_data:
  s3_data:
  s3_config:
